In [1]:
import pandas as pd
import os

df = pd.read_csv("C:\\Users\\ivano\\OneDrive\\Documents\\KEDGE\\MSC DATA\\Courses\\\Python bootcamp\\Python_Airbnb_project\\Denver dataset\\Description.csv")

In [2]:
df.head(5)

,id,name,summary,space,description,amenities,host_id,instant_bookable,require_guest_profile_picture,require_guest_phone_verification
0,360,LoHi Secret garden at the Chickadee Cottage,Come enjoy our oasis is the city and stay at o...,Chickadee Cottage is the largest of our guest ...,Come enjoy our oasis is the city and stay at o...,"{TV,Wifi,""Air conditioning"",Kitchen,""Free stre...",666,t,t,t
1,590,Comfortable - and a great value!,"Large guest room in my home, where I also live...",I have been enjoying welcoming many wonderful ...,"Large guest room in my home, where I also live...","{Internet,Wifi,""Air conditioning"",Kitchen,""Fre...",933,f,f,f
2,592,private,This room is in the basement. It does not hav...,This is a basement room. You can sometimes he...,This room is in the basement. It does not hav...,"{Internet,Wifi,""Air conditioning"",Kitchen,""Fre...",933,f,f,f
3,1940,Baker Studio Close to EVERYTHING,Great place for a few nights or months! Signif...,"This newly built, highly functional studio is ...",Great place for a few nights or months! Signif...,"{TV,Wifi,""Air conditioning"",Kitchen,""Pets live...",2150,f,f,f
4,2086,Garden Level Condo,"A furnished, garden level, one bedroom/one bat...",Furnished one bedroom condo. Pets with additio...,"A furnished, garden level, one bedroom/one bat...","{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",2284,f,f,f

In [3]:
import pandas as pd
import os

df_size = pd.read_csv("C:\\Users\\ivano\\OneDrive\\Documents\\KEDGE\\MSC DATA\\Courses\\\Python bootcamp\\Python_Airbnb_project\\Denver dataset\\Size.csv")

In [4]:
df_size.head()

,id,property_type,room_type,accommodates,bathrooms,bedrooms,beds
0,360,Guesthouse,Entire home/apt,4,1.0,2.0,3.0
1,590,House,Private room,3,1.0,1.0,1.0
2,592,House,Private room,2,1.0,1.0,1.0
3,1940,Guesthouse,Entire home/apt,2,1.0,0.0,1.0
4,2086,Apartment,Entire home/apt,2,1.0,1.0,1.0

In [5]:
acc_filter_value = input('How many people ?:\n')
df_size_filtered = df_size[df_size['accommodates'].isin([acc_filter_value])]

df_size_filtered

How many people ?:
4

Empty DataFrame
Columns: [id, property_type, room_type, accommodates, bathrooms, bedrooms, beds]
Index: []

In [6]:
import streamlit as st 
import pandas as pd

st.write(df_size)
df_result_search = pd.DataFrame() 


searchcheckbox_place_type = st.checkbox("Property type or room type ",value = False,key=1)
searchcheckbox_accomodates = st.checkbox("accommodates",value = False,key=2)

if searchcheckbox_place_type:
    property_type_search = st.text_input("property_type")
    room_type_search = st.text_input("room_type")
else:
    property_type_search = ''
    room_type_search = ''

if searchcheckbox_age:   
    acc_search = st.number_input("accommodates",min_value=0)
else:
    acc_search = 0

if st.button("search"):
    # 1. only property/room is checked
    if searchcheckbox_place_type and not searchcheckbox_accomodates:
        # if property is specified but not the room
        if property_type_search != '' and room_type_search == '':
            df_result_search = df_size[df_size['property_type'].str.contains(property_type_search, case=False, na=False)]
        # if room is specified but not the property
        elif name_search == '' and nickname_search != '':
            df_result_search = df_size[df_size['room_type'].str.contains(room_type_search, case=False, na=False)]
        # if both property and room are specified
        elif property_type_search != '' and room_type_search != '':
            df_result_search = df_size[(df_size['property_type'].str.contains(property_type_search, case=False, na=False)) & (df_size['room_type'].str.contains(room_type_search, case=False, na=False))]
        # if user does not enter anything
        else:
            st.warning('Please enter at least a property type or a room type')

    # 2. only accomodates is checked
    elif not searchcheckbox_place_type and searchcheckbox_accomodates:
        if acc_search != 0:
            df_result_search = df_size[df_size['accommodates'] == acc_search]
            
    # 3. if both property/room and age are checked
    else:
        pass  # continue here.

ModuleNotFoundError: No module named 'streamlit'

In [10]:
df_size_filtered = df_size.loc[(df_size["accommodates"] >= 4)]
df_size_filtered

,id,property_type,room_type,accommodates,bathrooms,bedrooms,beds
0,360,Guesthouse,Entire home/apt,4,1.0,2.0,3.0
7,56185,House,Entire home/apt,8,3.0,4.0,9.0
8,59631,Townhouse,Entire home/apt,4,2.5,2.0,2.0
14,142683,House,Entire home/apt,4,1.5,2.0,2.0
15,172196,House,Entire home/apt,10,4.0,5.0,7.0
...,...,...,...,...,...,...,...
4860,40440457,House,Entire home/apt,6,2.0,3.0,3.0
4861,40442282,Apartment,Entire home/apt,4,2.0,2.0,2.0
4862,40443443,Apartment,Entire home/apt,4,2.0,2.0,2.0
4863,40454518,Apartment,Entire home/apt,4,2.0,2.0,2.0
4864,40454863,Apartment,Entire home/apt,4,2.0,2.0,2.0

In [12]:
df_prices = pd.read_csv("C:\\Users\\ivano\\OneDrive\\Documents\\KEDGE\\MSC DATA\\Courses\\Python bootcamp\\Python_Airbnb_project\\Denver dataset\\Prices.csv")

df_prices

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ivano\\OneDrive\\Documents\\KEDGE\\MSC DATA\\Courses\\Python bootcamp\\Python_Airbnb_project\\Denver dataset\\Prices.csv'